# Generated by Django 4.2.11 on 2024-05-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0004_importantdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importantdate',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
