# Generated by Django 4.2.11 on 2024-05-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billboard', '0005_alter_importantdate_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='oath',
            field=models.TextField(blank=True, null=True),
        ),
    ]
